# Generated by Django 5.0.4 on 2024-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_delete_employee_receipt_file_alter_receipt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
